blueprint:
  name: Benachrichtigung bei niedrigem Batteriestand
  description: Sendet eine Benachrichtigung, wenn der Batteriestand eines Geräts unter einen bestimmten Wert fällt.
  domain: automation
  input:
    battery_entity:
      name: Batterie-Sensor
      description: Der Sensor, der den Batteriestand überwacht
      selector:
        entity:
          domain: sensor
          device_class: battery
    battery_level:
      name: Batteriestand-Schwellenwert
      description: Der Batteriestand, bei dem die Benachrichtigung ausgelöst wird
      default: 20
      selector:
        number:
          min: 5
          max: 50
          unit_of_measurement: "%"
    notify_service:
      name: Benachrichtigungsdienst
      description: Der Dienst, der für die Benachrichtigung verwendet werden soll (z.B. notify.mobile_app_iphone)
      selector:
        text:

trigger:
  - platform: numeric_state
    entity_id: !input battery_entity
    below: !input battery_level

condition: []

action:
  - service: !input notify_service
    data:
      title: "Niedriger Batteriestand"
      message: >
        Der Batteriestand von {{ state_attr(trigger.entity_id, 'friendly_name') }} 
        ist auf {{ states(trigger.entity_id) }}% gefallen.
